import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Providers } from "./_providers/ui/NextUiProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} h-[100dvh] bg-black`}>
        <Providers>
          <main className="flex flex-col items-start justify-center ">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </main>
        </Providers>
      </body>
    </html>
  );
}
